### ISSUE TITLE
Vignette tidy

### ISSUE THREAD

**Issue by nrennie** [Stat-Cook/deident#15]
- I would suggest re-ordering the vignettes to be in a more logical order e.g the "rationale" vignette should be at the top rather than in the middle of transformation examples, the the more advanced example "re-using" should be after the simple example.
- In Transformations vignette, capitalise title
- In "Options" section of transformation vignette, the code is commented out. Why? If you don't want the code to execute set eval to FALSE.
- In Transformations vignette, you say "To demonstrate the different transformation we supply a toy data set, df, comprising 26 " but none of the output is shown, so you don't actually show the transformation.

**Comment by Stat-Cook** [comment]
To track: 

* ~~I would suggest re-ordering the vignettes to be in a more logical order e.g the "rationale" vignette should be at the top rather than in the middle of transformation examples, the the more advanced example "re-using" should be after the simple example.~~
* ~~In Transformations vignette, capitalise title~~
* ~~In "Options" section of transformation vignette, the code is commented out. Why? If you don't want the code to execute set eval to FALSE.~~
* In Transformations vignette, you say "To demonstrate the different transformation we supply a toy data set, df, comprising 26 " but none of the output is shown, so you don't actually show the transformation.

**Comment by Stat-Cook** [comment]
@nrennie quick check - for ordering of vignettes.  Is this just ordering in the pkgdown documentation?

**Comment by nrennie** [comment]
@Stat-Cook Yes, doing that should also re-order them on the CRAN page: https://cran.r-project.org/web/packages/deident/index.html

**Comment by Stat-Cook** [comment]
@nrennie  we've updated the Transformations vignette to use the same `babynames` data as the paper (more realistic than the previous `df`).  Is it clear that, for each topic, the first block is the different ways to call the `deident` function, and then the practical examples follow?
